import { Product, ProductCategory } from '../types';

const calculateMarkup = (price: number) => Math.ceil(price * 1.10);

export const INITIAL_PRODUCTS: Product[] = [
  // Page 2
  {
    id: 'p1',
    code: 'NKT-031 1.8M',
    name: 'Executive Glass Top Table (1.8m)',
    category: ProductCategory.ExecutiveTable,
    originalPrice: 32470,
    sellingPrice: calculateMarkup(32470),
    dimensions: 'Front: L180cm x W80cm x H76cm',
    description: 'Modern, contemporary design for an office desk with glass top and steel frame painted in black color. Stainless steel leg frame.',
    images: ['https://images.unsplash.com/photo-1518455027359-f3f8164ba6bd?auto=format&fit=crop&q=80&w=800'],
    isLocked: true,
    isActive: true,
  },
  // Page 4
  {
    id: 'p2',
    code: 'JA A03-20',
    name: 'Executive Table (Curved Edge)',
    category: ProductCategory.ExecutiveTable,
    originalPrice: 29364,
    sellingPrice: calculateMarkup(29364),
    dimensions: 'Table: L200cm x W80cm x H75cm',
    description: 'High-tech vacuum forming process. PMMA veneer imported from South Korea. Hardness 4H. Soft-close drawer.',
    images: ['https://images.unsplash.com/photo-1595515106968-3d23194a319f?auto=format&fit=crop&q=80&w=800'],
    isLocked: true,
    isActive: true,
  },
  // Page 6
  {
    id: 'p3',
    code: 'SH102-16',
    name: 'L-Shape Executive Desk',
    category: ProductCategory.ExecutiveTable,
    originalPrice: 23066,
    sellingPrice: calculateMarkup(23066),
    dimensions: 'Table: L160cm x W72cm x H75cm',
    description: 'Melamine finish, Combi-lock drawer, Shelves, System Unit bin, Grommet.',
    images: ['https://images.unsplash.com/photo-1497215842964-222b4bef9726?auto=format&fit=crop&q=80&w=800'],
    isLocked: true,
    isActive: true,
  },
  // Page 47 - Racks
  {
    id: 'p4',
    code: 'XS-OD 120cm',
    name: 'Metal Rack 6 Layers',
    category: ProductCategory.FilingCabinet,
    originalPrice: 8935,
    sellingPrice: calculateMarkup(8935),
    dimensions: 'L120cm x W45cm x H200cm',
    description: 'Polyester Powdercoat finish treated with rust inhibiting base coat. Easy to assemble fully adjustable shelves. Capacity 120kg/shelf.',
    images: ['https://images.unsplash.com/photo-1595514020176-23b93df2df73?auto=format&fit=crop&q=80&w=800'],
    isLocked: true,
    isActive: true,
  },
  // Page 50 - Cabinets
  {
    id: 'p5',
    code: 'DGD4',
    name: '4-Drawer Filing Cabinet',
    category: ProductCategory.FilingCabinet,
    originalPrice: 8000,
    sellingPrice: calculateMarkup(8000),
    dimensions: 'L62cm x W46cm x H134cm',
    description: 'Powder coating finish. Superior gang drawer locking system. Can fit letter and legal size folder.',
    images: ['https://images.unsplash.com/photo-1522204523234-8729aa6e3d5f?auto=format&fit=crop&q=80&w=800'],
    isLocked: true,
    isActive: true,
  },
  // Page 82 - Chairs
  {
    id: 'p6',
    code: 'YS946-6 BLK',
    name: 'Fabric Office Chair',
    category: ProductCategory.OfficeChair,
    originalPrice: 2670,
    sellingPrice: calculateMarkup(2670),
    dimensions: 'L56cm x W46cm x H6cm',
    description: 'Upholstered in fabric, 360 swivel, Chrome plated star-base, Adjustable height.',
    images: ['https://images.unsplash.com/photo-1580480055273-228ff5388ef8?auto=format&fit=crop&q=80&w=800'],
    isLocked: true,
    isActive: true,
  },
  // Page 105 - Leather Chair
  {
    id: 'p7',
    code: '3009B',
    name: 'Jr. Executive Leatherette Chair',
    category: ProductCategory.OfficeChair,
    originalPrice: 6790,
    sellingPrice: calculateMarkup(6790),
    dimensions: 'L56cm x W51cm x H104cm',
    description: 'Upholstered in leather, Chrome plated star-base, Padded armrest, Lumbar support.',
    images: ['https://images.unsplash.com/photo-1505843490538-5133c6c7d0e1?auto=format&fit=crop&q=80&w=800'],
    isLocked: true,
    isActive: true,
  },
  // Page 79 - Gang Chair
  {
    id: 'p8',
    code: 'GC5STR',
    name: '5-Seater Gang Chair',
    category: ProductCategory.GangChair,
    originalPrice: 10970,
    sellingPrice: calculateMarkup(10970),
    dimensions: 'L286cm x W68cm x H77cm',
    description: 'Steel arm and leg frame with chrome plated finish. Powder coated beam. Perforated seat and back.',
    images: ['https://images.unsplash.com/photo-1505330622279-bf7d7fc918f4?auto=format&fit=crop&q=80&w=800'],
    isLocked: true,
    isActive: true,
  },
  // Page 152 - Sofa
  {
    id: 'p9',
    code: 'SS 801',
    name: 'Home Furniture (2-Seater Sofa)',
    category: ProductCategory.Sofa,
    originalPrice: 17195,
    sellingPrice: calculateMarkup(17195),
    dimensions: 'Double: L150cm W86cm H74cm',
    description: 'Back & seat with fabric cover. Frame with high-rebound springs & high density foam.',
    images: ['https://images.unsplash.com/photo-1555041469-a586c61ea9bc?auto=format&fit=crop&q=80&w=800'],
    isLocked: true,
    isActive: true,
  },
  // Page 74 - Conference
  {
    id: 'p10',
    code: 'SQ-1709 3.2m',
    name: 'Conference Table 3.2M',
    category: ProductCategory.ConferenceTable,
    originalPrice: 20170,
    sellingPrice: calculateMarkup(20170),
    dimensions: 'L320cm x W120cm x H75cm',
    description: 'MDF board, Tubular steel frame.',
    images: ['https://images.unsplash.com/photo-1611269154421-4e27233ac5c7?auto=format&fit=crop&q=80&w=800'],
    isLocked: true,
    isActive: true,
  }
];
